steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.api
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-api:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.ui
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-ui:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-ui:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-api:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-api:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-ui:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/sec-copilot-ui:latest
substitutions:
  _REGION: us-west1
  _AR_REPO: sec-copilot
  _IMAGE_TAG: latest
options:
  logging: CLOUD_LOGGING_ONLY
