apiVersion: v1
kind: Service
metadata:
  name: sec-copilot-api
  annotations:
    k8s.grafana.com/job: sec-copilot-api
    k8s.grafana.com/metrics.path: /metrics
    k8s.grafana.com/metrics.portNumber: "8000"
    k8s.grafana.com/scrape: "true"
